# General Jekyll Config
highlighter: rouge
url: http://blog.stekoe.de
lsi: false
excerpt_separator: "<!-- more -->"
gems:
  - jekyll-sitemap
  - jekyll-gist
exclude: [LICENSE, CNAME, README.md, .gitignore, Gemfile, Gemfile.lock]