# General Jekyll Config
highlighter: rouge
url: http://blog.stekoe.de
excerpt_separator: "<!-- more -->"
paginate: 5
related:
  min_score: 0.75
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
exclude:
  - LICENSE
  - CNAME
  - README.md
  - .gitignore
  - Gemfile
  - Gemfile.lock
